name: GlowingBlocks
version: 1.0.0
main: fr.skytasul.glowingentities.GlowingEntitiesPlugin
api-version: 1.21
author: TremeQ
description: A Paper plugin providing commands to use the GlowingEntities API for making blocks and NPCs glow.
website: https://github.com/tremeq/GlowingEntities

commands:
  glowblock:
    description: Make the block you are looking at glow
    usage: /<command> [color|rainbow] [global]
    aliases: [gb, glow]
    permission: glowingblocks.glowblock

  unglowblock:
    description: Stop the block you are looking at from glowing
    usage: /<command>
    aliases: [ugb, unglow]
    permission: glowingblocks.unglowblock

  glownpc:
    description: Make a Citizens NPC glow
    usage: /<command> <npc_id|name> [color|rainbow]
    aliases: [gnpc]
    permission: glowingblocks.glownpc

  unglownpc:
    description: Stop a Citizens NPC from glowing
    usage: /<command> <npc_id|name>
    aliases: [ugnpc]
    permission: glowingblocks.unglownpc

  glowingentities:
    description: Main plugin command
    usage: /<command> [reload|help|list|save]
    aliases: [ge, glowing]
    permission: glowingblocks.admin

softdepend: [Citizens]

permissions:
  glowingblocks.glowblock:
    description: Allows making blocks glow
    default: op

  glowingblocks.unglowblock:
    description: Allows removing glow from blocks
    default: op

  glowingblocks.glownpc:
    description: Allows making NPCs glow
    default: op

  glowingblocks.unglownpc:
    description: Allows removing glow from NPCs
    default: op

  glowingblocks.admin:
    description: Administrative commands
    default: op
